@startuml
title Kinobezdna
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

top to bottom direction

Person(user, "Пользователи Kinobezdna", "Используют мобильное устройство, ноутбук, Smart TV")

Container_Boundary(UserInteraction, "Kinobezdna") {

    Container(proxy_service, "Proxy Service", "Go API Gateway", "Маршрутизация запросов к монолитному приложению и микросервисам")

    Container(user_service, "Users Service", "Go Microservice", "Управление профилями пользователей")
    ContainerDb(db_users, "Users DB", "RDBMS", "База данных пользователей")
    Rel(user_service, db_users, "Храним профили пользователей")
    Rel(proxy_service, user_service, "Маршрутизация запросов к сервису пользователей")


    Container(video_service, "Video Service", "Go Microservice", "Обработка метаданных фильмов, жанров, рейтингов")
    ContainerDb(db_videos, "Videos DB", "RDBMS", "Каталог и метаданные фильмов")
    Rel(video_service, db_videos, "Сохраняем информацию о видео")
    Rel(proxy_service, video_service, "Запросы к контентному сервису")


    Container(subscriptions_service, "Subscriptions Service", "Go Microservice", "Управление тарифами. Списание платежей.")
    ContainerDb(db_subscriptions, "Subscriptions DB", "RDBMS", "Управляем тарифами")
    Rel(subscriptions_service, db_subscriptions, "Управляем тарифами")
    Rel(proxy_service, subscriptions_service, "Управление подписками")

    Container(payment_service, "Payment Service", "Go Microservice", "Обработка платежных транзакций. История платежей")
    ContainerDb(db_payments, "Payments DB", "RDBMS", "Хранит данные о платежах")
    Rel(payment_service, db_payments, "Ведём историю платежей")
    Rel(proxy_service, payment_service, "Обработка запросов на оплату")


    Container(recommendations_service, "Recommendations Service", "Go Microservice", "Сбор оценок. Механизм рекомендаций.")
    Rel(proxy_service, recommendations_service, "Отправка запросов к рекомендациям")

    Container(media_file_service, "Media File Service", "Go Microservice", "Файлы и мультимедиа. Загрузка файлов. Доставка контента")
    Rel(proxy_service, media_file_service, Сервис предоставления файлов")


    Container(payment_gateway, "Payment Gateway", "Go Microservice", "Шлюз для взаимодействия с платёжными системами")
    Rel(payment_service, payment_gateway, "Обработка оплаты через шлюз")


    Container(events_service, "Events Service", "Kafka", "Передача сообщений между компонентами")
    Rel(user_service, events_service, "Отправляет события изменения пользователей")
    Rel(video_service, events_service, "Отправляет события о просмотре фильмов")
    Rel(recommendations_service, events_service, "Получает обновления рейтингов")
    Rel(payment_service, events_service, "Оповещает о платежах")

}


Rel(user, proxy_service, "Отправляют HTTP-запросы")

Container_Ext(ext_cloud_storage, "Cloud Storage", "Облачное хранилище")
Rel(media_file_service, ext_cloud_storage, "Предоставление файлов из облака")

Container_Ext(ext_recommendations_services, "External Recommendations Services", "Внешние рекомендательные сервисы")
Rel(recommendations_service, ext_recommendations_services, "Отправляют HTTP-запросы")

Container_Ext(ext_payment_services, "External Payment Services", "Платёжный сервис")
Rel(payment_gateway, ext_payment_services, "Отправляют HTTP-запросы")

@enduml